import type { Metadata } from 'next'
import Navbar from '@/components/shared/navbar'
import Sidebar from '@/components/shared/sidebar'
import '../../globals.css'
import About from '@/components/shared/about'
import Footer from '@/components/shared/footer'

export const metadata: Metadata = {
    title: 'Manga',
    description: 'Generated by Zecht',
}

export default async function ProtectedLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                <Sidebar />
                {children}
                <About/>
                <Footer/>
            </body>
        </html>
    )
}