import type { Metadata } from 'next'
import '../../globals.css'

export const metadata: Metadata = {
    title: 'Admin',
    description: 'Generated by Zecht',
}

export default async function ProtectedLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    )
}