import { Metadata } from "next"
import '../globals.css'

export const metadata: Metadata = {
    title: 'Zeninga',
    description: 'Generated by create next app',
}

const AuthLayout = ({children}:{children: React.ReactNode}) => {
    return (
        <div className="h-full flex items-center justify-center bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-[#153067] to-zinc-900">
            {children}
        </div>
    )
}

export default AuthLayout