import type { Metadata } from 'next'
import Navbar from '@/components/shared/navbar'
import Sidebar from '@/components/shared/sidebar'

export const metadata: Metadata = {
    title: 'Home',
    description: 'Generated by Zecht',
}

export default async function ProtectedLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                <Sidebar />
                {children}
            </body>
        </html>
    )
}