import type { Metadata } from 'next'
import '../../globals.css'
import SettingNavbar from '@/components/shared/setting-navbar'

export const metadata: Metadata = {
    title: 'Profile',
    description: 'Generated by Zecht',
}

export default async function ProtectedLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <SettingNavbar />
                {children}
            </body>
        </html>
    )
}